export default [
  {
    id: 1323965,
    number: 1,
    name: "Восстановить подключение с вычислителем",
    perpetrator: {
      id: 1311862,
      email: "1.1@mail.ru",
      name: "Администратор УК Е.",
      cellphone: null,
      executingTaskCount: 1,
    },
    status: "Done",
    type: "Common",
    closingTime: "2020-03-06T13:51:19.895132",
  },
  {
    id: 1323963,
    number: 2,
    name: "Назначение исполнителя на полевое обследование",
    perpetrator: {
      id: 1311862,
      email: "1.1@mail.ru",
      name: "Администратор УК Е.",
      cellphone: null,
      executingTaskCount: 1,
    },
    status: "InProgress",
    type: "Common",
    closingTime: null,
  },
  {
    id: 1323962,
    number: 3,
    name: "Проведение полевого обследования прибора",
    perpetrator: null,
    status: "Waiting",
    type: "Common",
    closingTime: null,
  },
  {
    id: 1323961,
    number: 4,
    name: "Определение типа работ по преобразователю",
    perpetrator: null,
    status: "Waiting",
    type: "Switch",
    closingTime: null,
  },
]
